#config_version=5


#      __  ___          __                __  __                  __ 
#     /  |/  /___  ____/ /__  _    ____ _/ /_/ /__________ ______/ /_
#    / /|_/ / __ \/ __  / _ \(_)  / __ `/ __/ __/ ___/ __ `/ ___/ __/
#   / /  / / /_/ / /_/ /  __/    / /_/ / /_/ /_/ /  / /_/ / /__/ /_  
#  /_/  /_/\____/\__,_/\___(_)   \__,_/\__/\__/_/   \__,_/\___/\__/  
#                                                                    

# A completely rubbish attract mode that just blinks 3 lights
# TODO - make it better!
show_player:
  mode_attract_started: attract_display_loop
  mode_attract_started.1: 
      done:
         speed: 50
  mode_attract_started.2: 
     attract_segment_loop_lower:
        speed: 20
  mode_attract_started.3: 
     attract_segment_loop_upper:
        speed: 10
         
#segment_display_player:
#   mode_attract_started:
#      player1_display:
#         text: "Pinball"
#      player2_display:
#         text: "is fun"
#      player3_display:
#         text: "1234567"
#      player4_display:
#         text: "890 APC"