#config_version=5


#      __  ___          __                __  __                  __ 
#     /  |/  /___  ____/ /__  _    ____ _/ /_/ /__________ ______/ /_
#    / /|_/ / __ \/ __  / _ \(_)  / __ `/ __/ __/ ___/ __ `/ ___/ __/
#   / /  / / /_/ / /_/ /  __/    / /_/ / /_/ /_/ /  / /_/ / /__/ /_  
#  /_/  /_/\____/\__,_/\___(_)   \__,_/\__/\__/_/   \__,_/\___/\__/  
#                                                                    

# A completely rubbish attract mode that just blinks 3 lights
# TODO - make it better!
show_player:
  mode_attract_started: attract_display_loop
  #mode_attract_started.1: attract_light_show