#config_version=5


#      __  ___          __          __                  
#     /  |/  /___  ____/ /__  _    / /_  ____ _________ 
#    / /|_/ / __ \/ __  / _ \(_)  / __ \/ __ `/ ___/ _ \
#   / /  / / /_/ / /_/ /  __/    / /_/ / /_/ (__  )  __/
#  /_/  /_/\____/\__,_/\___(_)  /_.___/\__,_/____/\___/ 
#                                                       

# All the basic things that the game needs to handle when a ball is in play.
# TODO - move the TOMCAT target handling into it's own mode

mode:
   start_events: ball_starting
   priority: 100

# Some scoring which is independant of the mode we're in
variable_player:
    s_outlaneRight_active:
       score: 5000
    s_outlaneLeft_active:
       score: 5000
    s_inlaneLeft_active:
       score: 1000
    s_inlaneRight_active:
       score: 1000
    s_rightRescue_active:  # rescue mode will award additional 
       score: 500
    s_leftRescue_active:
       score: 500
    s_slingL_active:
       score: 10
    s_slingR_active:
       score: 10
    tomcat_flashing_hit:
       score: 1000
    tomcat_lit_hit:
       score: 100
       

# Need to switch the flippers on and off (System 11!)
event_player:
   mode_base_started:
      - flipper_on
   mode_base_ended:
      - flipper_off

      
         
slide_player:
  mode_base_started:
      slide1:
        target: dmd
        widgets:
          - type: text
            text: (score)
            number_grouping: true
            min_digits: 2
            font_size: 15
      slide2:
         target: dmd_mini
         widgets:
          - type: text
            text: PLAYER (number)
            color: deepskyblue
            y: 9
            x: 1
            font_size: 8
            anchor_x: left
            anchor_y: bottom
            font_name: fixed_01
          - type: text
            color: red
            text: BALL   (ball)
            y: 1
            x: 1
            anchor_x: left
            anchor_y: bottom
            font_size: 8
            font_name: fixed_01
          - type: text
            color: orange
            text: BONUS (bonus_score)
            y: 18
            x: 1
            anchor_x: left
            anchor_y: bottom
            font_size: 8
            font_name: fixed_01
  tomcat_lit_complete:
     slide_tomcat:
        target: dmd
        expire: 1s
        widgets:
          - type: text
            text: TOMCAT
            font_size: 15
            color: blue

# The rest of this handles the TOMCAT targets
# TODO - move to own mode and comment properly        
shots:
  tomcat_t:
    switches: s_lowerLeftT s_upperLeftT
    show_tokens: 
       lights: l_lowerLeftT l_upperLeftT
    profile: tomcat_profile 
  tomcat_o:
    switches: s_lowerLeftO s_upperLeftO
    show_tokens: 
       lights: l_lowerLeftO l_upperLeftO
    profile: tomcat_profile 
  tomcat_m:
    switches: s_lowerLeftM s_upperLeftM
    show_tokens: 
       lights: l_lowerLeftM l_upperLeftM
    profile: tomcat_profile 
  tomcat_c:
    switches: s_lowerRightC s_upperRightC
    show_tokens: 
       lights: l_lowerRightC l_upperRightC
    profile: tomcat_profile 
  tomcat_a:
    switches: s_lowerRightA s_upperRightA
    show_tokens: 
       lights: l_lowerRightA l_upperRightA
    profile: tomcat_profile   
  tomcat_second_t:
    switches: s_lowerRightT s_upperRightT
    show_tokens: 
       lights: l_lowerRightT l_upperRightT
    profile: tomcat_profile 

    
    
shot_profiles:
  tomcat_profile:
    states:
      - name: flashing  # step 1
        show: flash
        speed: 6
      - name: lit  # step 2
        show: on
    loop: false
    
           
shot_groups:
   tomcat: 
      shots: tomcat_t tomcat_o tomcat_m tomcat_c tomcat_a tomcat_second_t 
      restart_events: tomcat_lit_complete

        