#config_version=5
#We track the player bonus as a number between 1 and 127
 

mode:
   start_events: ball_starting
   priority: 100
   
variable_player:
   mode_bonus_manager_started:
      bonus_score:
         action: set
         int: 0
      bonus_multiplier:
         action: set
         int: 2
   add_to_bonus:
      bonus_score: 1

event_player:
   inc_bonus_default_hit{current_player.bonus_score < 127}:
      - add_to_bonus

shots:
  inc_bonus:
    switches: s_outlaneLeft s_outlaneRight
    restart_events: inc_bonus_default_hit
    
show_player:
  player_bonus_score:
      off:
         key: 1K
         show_tokens: 
            light: l_bonus1K     
  player_bonus_score{current_player.bonus_score % 2 == 1}:
      on:
         key: 1K
         show_tokens: 
            light: l_bonus1K
  logicblock_bonus_count_2K_updated{value < 2}:
      off:
         key: 2K
         show_tokens: 
            light: l_bonus2K
  logicblock_bonus_count_2K_updated{value >= 2}:
      on:
         key: 2K
         show_tokens: 
            light: l_bonus2K            
  logicblock_bonus_count_4K_updated{value < 4}:
      off:
         key: 4K
         show_tokens: 
            light: l_bonus4K
  logicblock_bonus_count_4K_updated{value >= 4}:
      on:
         key: 4K
         show_tokens: 
            light: l_bonus4K            
  logicblock_bonus_count_8K_updated{value < 8}:
      off:
         key: 8K
         show_tokens: 
            light: l_bonus8K
  logicblock_bonus_count_8K_updated{value >= 8}:
      on:
         key: 8K
         show_tokens: 
            light: l_bonus8K
  logicblock_bonus_count_16K_updated{value < 16}:
      off:
         key: 16K
         show_tokens: 
            light: l_bonus16K
  logicblock_bonus_count_16K_updated{value >= 16}:
      on:
         key: 16K
         show_tokens: 
            light: l_bonus16K
  logicblock_bonus_count_32K_updated{value < 32}:
      off:
         key: 32K
         show_tokens: 
            light: l_bonus32K
  logicblock_bonus_count_32K_updated{value >= 32}:
      on:
         key: 32K
         show_tokens: 
            light: l_bonus32K
  logicblock_bonus_count_64K_updated{value >= 64}:
      on:
         key: 64K
         show_tokens: 
            light: l_bonus64K
  

            
counters:
   bonus_count_1K:
      count_events: add_to_bonus
      starting_count: 0
      count_complete_value: 1
      direction: up
      disable_on_complete: false  
   bonus_count_2K:
      count_events: add_to_bonus
      starting_count: 0
      count_complete_value: 4
      direction: up
      disable_on_complete: false
   bonus_count_4K:
      count_events: add_to_bonus
      starting_count: 0
      count_complete_value: 8
      direction: up        
      disable_on_complete: false
   bonus_count_8K:
      count_events: add_to_bonus
      starting_count: 0
      count_complete_value: 16
      direction: up        
      disable_on_complete: false   
   bonus_count_16K:
      count_events: add_to_bonus
      starting_count: 0
      count_complete_value: 32
      direction: up        
      disable_on_complete: false   
   bonus_count_32K:
      count_events: add_to_bonus
      starting_count: 0
      count_complete_value: 64
      direction: up        
      disable_on_complete: false
   bonus_count_64K:
      count_events: add_to_bonus
      starting_count: 0
      count_complete_value: 128
      direction: up        
      disable_on_complete: false      