#config_version=5


#      __  ___          __          __                                                                           
#     /  |/  /___  ____/ /__  _    / /_  ____  ____  __  _______     ____ ___  ____ _____  ____ _____ ____  _____
#    / /|_/ / __ \/ __  / _ \(_)  / __ \/ __ \/ __ \/ / / / ___/    / __ `__ \/ __ `/ __ \/ __ `/ __ `/ _ \/ ___/
#   / /  / / /_/ / /_/ /  __/    / /_/ / /_/ / / / / /_/ (__  )    / / / / / / /_/ / / / / /_/ / /_/ /  __/ /    
#  /_/  /_/\____/\__,_/\___(_)  /_.___/\____/_/ /_/\__,_/____/____/_/ /_/ /_/\__,_/_/ /_/\__,_/\__, /\___/_/     
#                                                           /_____/                           /____/             

# The end of ball bonus on F-14 is a multiple of 1000, minimum value is 0 and maximum is 127,000
# Counting it is simple, but displaying it is tricky as there are 7 lamps on the playfield used to
# show it.  1K, 2K, 4K, 8K, 16K, 32K and 64K.  You add up all the lit lamps to determine the total
# Internally we track the bonus as a number between 0 and 127, it gets multplied by 1000 before being awarded


 

mode:
   start_events: ball_starting
   priority: 100
   
variable_player:
   mode_bonus_manager_started:
      bonus_score:
         action: set
         int: 0
      bonus_multiplier:
         action: set
         int: 1
   add_to_bonus:
      bonus_score: 1
   add_to_multiplier{current_player.bonus_multiplier < 8}:
      bonus_multiplier: 1

# Use a simple local event so long as we didn't get to 127 yet
event_player:
   inc_bonus_default_hit{current_player.bonus_score < 127}:
      - add_to_bonus

# all the switches that can increment the bonus
# maybe change this to events later....
shots:
  inc_bonus: 
    switches: s_outlaneLeft s_outlaneRight
    restart_events: inc_bonus_default_hit
    
# Displaying the bonus on the lamps involves a complicated set of counters and shows.  
# TODO - put more comments in here    
show_player:
  player_bonus_score:
      off:
         key: 1K
         show_tokens: 
            light: l_bonus1K     
  player_bonus_score{current_player.bonus_score % 2 == 1}:
      on:
         key: 1K
         show_tokens: 
            light: l_bonus1K
  logicblock_bonus_count_2K_updated{value < 2}:
      off:
         key: 2K
         show_tokens: 
            light: l_bonus2K
  logicblock_bonus_count_2K_updated{value >= 2}:
      on:
         key: 2K
         show_tokens: 
            light: l_bonus2K            
  logicblock_bonus_count_4K_updated{value < 4}:
      off:
         key: 4K
         show_tokens: 
            light: l_bonus4K
  logicblock_bonus_count_4K_updated{value >= 4}:
      on:
         key: 4K
         show_tokens: 
            light: l_bonus4K            
  logicblock_bonus_count_8K_updated{value < 8}:
      off:
         key: 8K
         show_tokens: 
            light: l_bonus8K
  logicblock_bonus_count_8K_updated{value >= 8}:
      on:
         key: 8K
         show_tokens: 
            light: l_bonus8K
  logicblock_bonus_count_16K_updated{value < 16}:
      off:
         key: 16K
         show_tokens: 
            light: l_bonus16K
  logicblock_bonus_count_16K_updated{value >= 16}:
      on:
         key: 16K
         show_tokens: 
            light: l_bonus16K
  logicblock_bonus_count_32K_updated{value < 32}:
      off:
         key: 32K
         show_tokens: 
            light: l_bonus32K
  logicblock_bonus_count_32K_updated{value >= 32}:
      on:
         key: 32K
         show_tokens: 
            light: l_bonus32K
  logicblock_bonus_count_64K_updated{value >= 64}:
      on:
         key: 64K
         show_tokens: 
            light: l_bonus64K
  player_bonus_multiplier{value==2}:
      on:
         key: multiplier
         show_tokens:
            lights: l_bonus2X
  player_bonus_multiplier{value==3}:
      on:
         key: multiplier
         show_tokens:
            lights: l_bonus2X l_bonus3X
  player_bonus_multiplier{value==4}:
      on:
         key: multiplier
         show_tokens:
            lights: l_bonus2X l_bonus3X l_bonus4X
  player_bonus_multiplier{value==5}:
      on:
         key: multiplier
         show_tokens:
            lights: l_bonus2X l_bonus3X l_bonus4X l_bonus5X
  player_bonus_multiplier{value==6}:
      on:
         key: multiplier
         show_tokens:
            lights: l_bonus2X l_bonus3X l_bonus4X l_bonus5X l_bonus6X
  player_bonus_multiplier{value==7}:
      on:
         key: multiplier
         show_tokens:
            lights: l_bonus2X l_bonus3X l_bonus4X l_bonus5X l_bonus6X l_bonus7X
  player_bonus_multiplier{value==8}:
      on:
         key: multiplier
         show_tokens:
            lights: l_bonus2X l_bonus3X l_bonus4X l_bonus5X l_bonus6X l_bonus7X l_bonus8X

            
counters:
   bonus_count_1K:
      count_events: add_to_bonus
      starting_count: 0
      count_complete_value: 1
      direction: up
      disable_on_complete: false  
   bonus_count_2K:
      count_events: add_to_bonus
      starting_count: 0
      count_complete_value: 4
      direction: up
      disable_on_complete: false
   bonus_count_4K:
      count_events: add_to_bonus
      starting_count: 0
      count_complete_value: 8
      direction: up        
      disable_on_complete: false
   bonus_count_8K:
      count_events: add_to_bonus
      starting_count: 0
      count_complete_value: 16
      direction: up        
      disable_on_complete: false   
   bonus_count_16K:
      count_events: add_to_bonus
      starting_count: 0
      count_complete_value: 32
      direction: up        
      disable_on_complete: false   
   bonus_count_32K:
      count_events: add_to_bonus
      starting_count: 0
      count_complete_value: 64
      direction: up        
      disable_on_complete: false
   bonus_count_64K:
      count_events: add_to_bonus
      starting_count: 0
      count_complete_value: 128
      direction: up        
      disable_on_complete: false      