#config_version=5
# Second sortie V2
config:
   - display.yaml
   - prochardware.yaml
   - devices.yaml
   - kickback.yaml
   - simple_shows.yaml
#   - smart_matrix.yaml
#   - real_dmd.yaml

player_vars:
   rescue_enabled:
      initial_value: 0
   rescue_target_state:
      initial_value: OFF
      value_type: str
   kickback_status:
      initial_value: OFF
      value_type: str
   bonus_score:
      initial_value: 0
   lit_target:
      initial_value: 1
   left_multiplier_lit:
      initial_value: False
      value_type: str
   right_multiplier_lit:
      initial_value: False
      value_type: str
   spinner_2K_lit:
      initial_value: False
      value_type: str


settings:
   tomcat_spot_both:
      label: Spot Both Tomcat Letters
      key_type: str
      values: 
         YES: Spot both letters
         NO: Spot single letter
      default: YES
      sort: 100

modes:
   - base
   - rescue
   - targets1_6
   - bonus
   - bonus_manager
   - orbit

virtual_platform_start_active_switches:
   - s_trough1
   - s_trough2
   - s_trough3
   - s_trough4

     
playfields:
   playfield:
       default_source_device: bd_plunger_lane
       tags: default
      
keyboard:
   z:
      switch:   s_left_inlane
   x:
      switch:   s_right_inlane
   s:
      switch:   s_startButton