#config_version=5


#     ______            _____                __          _               
#    / ____/___  ____  / __(_)___ __    ____/ /__ _   __(_)_______  _____
#   / /   / __ \/ __ \/ /_/ / __ `(_)  / __  / _ \ | / / / ___/ _ \/ ___/
#  / /___/ /_/ / / / / __/ / /_/ /    / /_/ /  __/ |/ / / /__/  __(__  ) 
#  \____/\____/_/ /_/_/ /_/\__, (_)   \__,_/\___/|___/_/\___/\___/____/  
#                         /____/                                         

# At the moment the 2 divertors are in here and we'll let MPF handle them.  
# Once we get to sorting out multiball we might need to get more clever
ball_devices:
   bd_drain:
      ball_switches: s_outhole
      eject_coil: c_outholeKicker
      eject_targets: bd_trough
      tags: drain
   bd_trough:
      ball_switches: s_trough1 s_trough2 s_trough3 s_trough4
      eject_coil: c_troughEject
      eject_targets: bd_plunger_lane
      tags: home, trough 
   bd_plunger_lane:
      ball_switches: s_shooter
      mechanical_eject: true
      eject_coil: c_autoLaunch
      entrance_count_delay: 1s
      eject_targets: bd_lock1, bd_lock2, bd_lock3
   bd_lock1:
      ball_switches: s_lock1
      eject_coil: c_lock1_eject
      request_ball_events: catch1
   bd_lock2:
      ball_switches: s_lock2
      eject_coil: c_lock2_eject
      request_ball_events: catch2
   bd_lock3:
      ball_switches:  s_lock3
      eject_coil: c_lock3_eject
      request_ball_events: catch3
   bd_vuk:
      ball_switches: s_vUK
      eject_coil: c_upKicker
      eject_targets: bd_lock1, bd_lock2, bd_lock3

      
diverters:
   top_diverter:
      activation_coil: c_upperDivertor
      activation_time: 3s
      #activation_switches: s_rampEntry
      activate_events: send_to_mid_right_lock
      targets_when_active: bd_lock2
      targets_when_inactive: bd_lock1, bd_lock3
      feeder_devices: bd_vuk, bd_plunger_lane
   lower_diverter:
      activation_time: 3s
      #activation_switches: s_rampEntry
      activation_coil: c_lowerDivertor
      targets_when_active: bd_lock1
      targets_when_inactive: bd_lock3
      feeder_devices: bd_vuk, bd_plunger_lane
      
      