#config_version=5

hardware:
    rgb_dmd: smartmatrix

displays:
   dmd:
      width: 128
      height: 32
   dmd_mini:
      width: 64
      height: 32
   laptop:
      width: 1200
      height: 192

window:
   width: 1200
   height: 192
   effects:
      type: color_dmd
      dot_size: 1.0
   left: 15
   top : 830
   borderless: no
   source_display: laptop   
   title: 'F14 TOMCAT - Second Sortie'   

slides:
   base_slide:
      - type: display
        source_display: dmd
        width: 768
        height: 192
        x: left
        anchor_x: left
        #y: 0
      - type: display
        source_display: dmd_mini
        width: 256
        height: 128
        x: right
        anchor_x: right
        #y: -50
        
slide_player:
   mc_ready: 
      base_slide:
         target: laptop
       
      
smartmatrix:
    smartmatrix_1:
       port: com3
       baud: 2500000
       old_cookie: false
    smartmatrix_2:
       port: com5
       baud: 2500000
       old_cookie: false
       
rgb_dmds:
  smartmatrix_1:
     platform: smartmatrix
     brightness: .5
     source_display: dmd
     fps: 25      
  smartmatrix_2:
     platform: smartmatrix
     only_send_changes: true
     brightness: .5
     source_display: dmd_mini
     fps: 25      