#config_version=5



#     ______            _____                ___            __           
#    / ____/___  ____  / __(_)___ __    ____/ (_)________  / /___ ___  __
#   / /   / __ \/ __ \/ /_/ / __ `(_)  / __  / / ___/ __ \/ / __ `/ / / /
#  / /___/ /_/ / / / / __/ / /_/ /    / /_/ / (__  ) /_/ / / /_/ / /_/ / 
#  \____/\____/_/ /_/_/ /_/\__, (_)   \__,_/_/____/ .___/_/\__,_/\__, /  
#                         /____/                 /_/            /____/   

# Put in the screen based displays.  Physical displays are handled in smart_matrix.yaml and real_dmd.yaml

displays:
   dmd:
      width: 128
      height: 32
   dmd_mini:
      width: 64
      height: 32
   laptop:
      width: 1200
      height: 192

window:
   width: 1200
   height: 192
   effects:
      type: color_dmd
      dot_size: 1.0
   left: 15
   top : 830
   borderless: no
   source_display: laptop   
   title: 'F14 TOMCAT - Second Sortie'   

slides:
   base_slide:
      - type: display
        source_display: dmd
        width: 768
        height: 192
        x: left
        anchor_x: left
        #y: 0
      - type: display
        source_display: dmd_mini
        width: 256
        height: 128
        x: right
        anchor_x: right
        #y: -50
        
slide_player:
   mc_ready: 
      base_slide:
         target: laptop
       
      
