#config_version=5

autofire_coils:
   rescue_kickback:
      coil: c_rescueKickBack
      switch: s_outlaneLeft
      enable_events: rescue_enabled
      debug: true
      ball_search_order: 0
      disable_events: rescue_off
