#config_version=5


#     ______            _____                                  __                   __                       
#    / ____/___  ____  / __(_)___ __    ____  _________  _____/ /_  ____ __________/ /      ______ _________ 
#   / /   / __ \/ __ \/ /_/ / __ `(_)  / __ \/ ___/ __ \/ ___/ __ \/ __ `/ ___/ __  / | /| / / __ `/ ___/ _ \
#  / /___/ /_/ / / / / __/ / /_/ /    / /_/ / /  / /_/ / /__/ / / / /_/ / /  / /_/ /| |/ |/ / /_/ / /  /  __/
#  \____/\____/_/ /_/_/ /_/\__, (_)  / .___/_/   \____/\___/_/ /_/\__,_/_/   \__,_/ |__/|__/\__,_/_/   \___/ 
#                         /____/    /_/                                                                      


hardware:
    platform: p_roc
    driverboards: wpc
    coils: snux
    lights: fadecandy

system11:
    ac_relay_delay_ms: 75
    ac_relay_driver: c_acSelect

snux:
    flipper_enable_driver: c_flipperEnable
    diag_led_driver: c_diagLED
    platform:

light_stripes:
   gi_lamp:
      number_start: 128
      count: 40
      light_template:
         tags: gi
         platform: fadecandy
   radar:
      number_start: 64
      count: 10
      light_template:
         tags: radar
         type: grb
         platform: fadecandy

lights:
    l_lightLockOn:
        number: L11
        label: 'Lites Lock On'
        platform: p_roc
    l_lightRelease:
        number: L12
        label: 'Lites Release'
        platform: p_roc
    l_blueSpecial:
        number: L13
        label: 'Hot Streak'
        platform: p_roc
    l_flyAgain:
        number: L14
        label: 'Fly Again'
        platform: p_roc
    l_leftRescue:
        number: L15
        label: 'Left Rescue'
        platform: p_roc
    l_kill:
        number: 7
        label: 'Centre Kill'
        platform: fadecandy
        type: grb
    l_rightRescue:
        number: L17
        label: 'Right Rescue'
        platform: p_roc
    l_kickBack:
        number: L18
        label: 'Rescue'
        platform: p_roc
    l_kill1:
        number: 0
        label: 'Alpha Kill'
        platform: fadecandy
    l_kill2:
        number: 1
        label: 'Bravo Kill'
        platform: fadecandy
    l_kill3:
        number: 2
        label: 'Charlie Kill'
        platform: fadecandy
    l_kill4:
        number: 3
        label: 'Delta Kill'
        platform: fadecandy
    l_kill5:
        number: 4
        label: 'Echo Kill'
        platform: fadecandy 
    l_kill6:
        number: 5
        label: 'Fox Kill'
        platform: fadecandy
    l_kill7:
        number: 6
        label: 'Golf Kill'
        platform: fadecandy
    l_insurance:
        number: L28
        label: 'Insurance'
        platform: p_roc
    l_bonus1K:
        number: L31
        label: '1K'
        platform: p_roc
    l_bonus2K:
        number: L32
        label: '2K'
        platform: p_roc
    l_bonus4K:
        number: L33
        label: '4K'
        platform: p_roc
    l_bonus8K:
        number: L34
        label: '8K'
        platform: p_roc
    l_bonus16K:
        number: L35
        label: '16K'
        platform: p_roc
    l_bonus32K:
        number: L36
        label: '32K'
        platform: p_roc
    l_bonus64K:
        number: L37
        label: '64K'
        platform: p_roc
    l_special:
        number: L38
        label: 'Special'
        platform: p_roc
    l_bonus2X:
        number: L41
        label: '2X'
        platform: p_roc
    l_bonus3X:
        number: L42
        label: '3X'
        platform: p_roc
    l_bonus4X:
        number: L43
        label: '4X'
        platform: p_roc
    l_bonus5X:
        number: L44
        label: '5X'
        platform: p_roc
    l_bonus6X:
        number: L45
        label: '6X'
        platform: p_roc
    l_bonus7X:
        number: L46
        label: '7X'
        platform: p_roc
    l_bonus8X:
        number: L47
        label: '8X'
        platform: p_roc
    l_bonusXLeft:
        number: L48
        label: 'Bonus X Left'
        platform: p_roc
    l_lowerLeftT:
        number: L51
        label: 'Lower Left T'
        platform: p_roc
    l_lowerLeftO:
        number: L52
        label: 'Lower Left O'
        platform: p_roc
    l_lowerLeftM:
        number: L53
        label: 'Lower Left M'
        platform: p_roc
    l_lowerRightT:
        number: L54
        label: 'Lower Right T'
        platform: p_roc
    l_lowerRightA:
        number: L55
        label: 'Lower Right A'
        platform: p_roc
    l_lowerRightC:
        number: L56
        label: 'Lower Right C'
        platform: p_roc
    l_inLanes:
        number: L57
        label: 'Inlanes x 2'
        platform: p_roc
    l_landing:
        number: L58
        label: 'Landing'
        platform: p_roc
    l_target3:
        number: 12
        label: 'Target - 3'
        platform: fadecandy
        type: grb
    l_target2:
        number: 13
        label: 'Target - 2'
        platform: fadecandy
        type: grb
    l_target1:
        number: 14
        label: 'Target - 1'
        platform: fadecandy
        type: grb
    l_target4:
        number: 11
        label: 'Target - 4'
        platform: fadecandy
        type: grb
    l_target5:
        number: 8
        label: 'Target - 5'
        platform: fadecandy
        type: grb
    l_target6:
        number: 10
        label: 'Target - 6'
        platform: fadecandy
        type: grb
    l_release:
        number: 9
        label: 'Release'
        platform: fadecandy
        type: grb
    l_lockOn:
        number: L68
        label: 'Lock On'
        platform: p_roc
    l_upperLeftT:
        number: L71
        label: 'Upper Left T'
        platform: p_roc
    l_upperLeftO:
        number: L72
        label: 'Upper Left O'
        platform: p_roc
    l_upperLeftM:
        number: L73
        label: 'Upper Left M'
        platform: p_roc
    l_upperRightT:
        number: L74
        label: 'Upper Right T'
        platform: p_roc
    l_upperRightA:
        number: L75
        label: 'Upper Right A'
        platform: p_roc
    l_upperRightC:
        number: L76
        label: 'Upper Right C'
        platform: p_roc
    l_bonusXRight:
        number: L77
        label: 'Bonus X Right'
        platform: p_roc
    l_spinner2K:
        number: L78
        label: 'Spinner 2K'
        platform: p_roc
    l_upperLock:
        number: L81
        label: 'Upper Lock'
        platform: p_roc
    l_middleLock:
        number: L82
        label: 'Centre Lock'
        platform: p_roc
    l_lowerLock:
        number: L83
        label: 'Lower Lock'
        platform: p_roc
    l_upperLanding:
        number: L84
        label: 'Upper Landing'
        platform: p_roc
    l_middleLanding:
        number: L85
        label: 'Centre Landing'
        platform: p_roc
    l_lowerLanding:
        number: L86
        label: 'Lower Landing'
        platform: p_roc
    l_ripOff:
        number: 15
        label: 'Rip Off'
        platform: fadecandy
        type: grb
    l_extraBall:
        number: L88
        label: 'Extra Ball'
        platform: p_roc


coils:
    c_outholeKicker:
        number: C01a
        label: 'Outhole'
        default_pulse_ms: 30
    c_flasher1:
       number: C01c
       label: 'Flasher 1'
    c_troughEject:
        number: C02a
        tags: trough_eject
        default_pulse_ms: 30
        label: 'Trough Eject'
    c_flasher2:
        number: C02c
        label: 'Flasher 2'
    c_upKicker:
        number: C03a
        label: 'Ball Popper'
    c_flasher3:
        number: C03c
        pulse_events: rescue_complete{state=='lit'}
        label: 'Flasher 3'
        default_pulse_ms: 200ms
    c_flasher4:
        number: C04c
        label: 'Flasher 4'
        pulse_events: rescue_complete{ state=='lit'}
        default_pulse_ms: 200ms
    c_midRightEject:
        number: C05a
        label: 'Center Right Eject'
        default_pulse_ms: 200ms
    c_flasher5:
        number: C05c
        label: 'Flasher 5'
        pulse_events: rescue_complete{ state=='lit'}
        default_pulse_ms: 200ms
    c_knocker:
        number: C06a
        label: 'Knocker'
    c_flasher6:
        number: C06c
        label: 'Flasher 6'
    c_rightEject:
        number: C07a
        label: 'Right Eject'
    c_flasher7:
        number: C07c
        label: 'Flasher 7'
    c_flasher8:
        number: C08c
        label: 'Flasher 8'
    c_flasher9:
        number: C09
        label: 'Flasher 9'
    c_midLeftEject:
        number: C10
        label: 'Centre Left Eject'
    c_gi:
        number: C11
        label: 'General Illum'
    c_yagovKickBack:
        number: C12
        label: 'Yagov Kickback'
        #platform: p_roc
    c_rescueKickBack:
        number: C13
        label: 'Rescue Kickback'
        platform: p_roc
    c_acSelect:
        number: C14
        label: 'A/C Select'
        allow_enable: true
    c_flasher10:
        number: C15
        label: 'Flasher 10'
    c_beacons:
        number: C16
        label: 'Beacons'
        allow_enable: true
    c_leftKicker:
        number: C17
        label: 'Left Sling'
    c_rightKicker:
        number: C18
        label: 'Right Sling'
    c_autoLaunch:
        number: C19
        label: 'Ball Auto Launch'
        default_pulse_ms: 500ms
    c_jetBumper:
        number: C20
        label: 'Pop Bumper'
    c_upperDivertor:
        number: C21
        label: 'Upper Divertor'
        allow_enable: true
    c_lowerDivertor:
        number: C22
        label: 'Lower Divertor'
        allow_enable: true
    c_flipperEnable:
        number: C23
        label: 'Flipper Enable'
        allow_enable: true
        enable_events: flipper_on
        disable_events: flipper_off
    c_diagLED: 
        number: C24
        allow_enable: true
        file_log: none
        console_log: none

switches:
    s_flipperLwR:
        number: S27
        label: 'Left Flipper EOS'
    s_flipperLwL:
        number: S87
        label: 'Right Flipper EOS'
    s_coinLeft:
        number: S16
        label: 'Left Coin Slot'
    s_coinCenter:
        number: S15
        label: 'Center Coin Slot'
    s_coinRight:
        number: S14
        label: 'Right Coin Slot'
    s_upSys11:
        number: SD8
    s_downSys11:
        number: SD2
    s_enterSys11:
        number: SD5
    s_exitSys11:
        number: SD0
    s_startButton:
        number: S13
        label: 'Start Button'
        tags: start
    s_tilt:
        number: S11
        label: 'Tilt'
    s_outlaneLeft:
        number: S85
        label: 'Left Outlane'
        tags: early_save
    s_inlaneLeft:
        number: S83
        label: 'Left Inlane'
        tags: playfield_active
    s_inlaneRight:
        number: S84
        label: 'Right Inlane'
        tags: playfield_active
    s_outlaneRight:
        number: S86
        tags: early_save, playfield_active
        label: 'Right Outlane'
    s_slamTilt:
        number: S17
        label: 'Slam Tilt'
    s_outhole:
        number: S22
        label: 'Outhole'
    s_trough4:
        number: S23
        label: 'Right Ball Trough'
    s_trough2:
        number: S24
        label: 'Right Center Ball Trough'
    s_trough3:
        number: S25
        label: 'Left Center Ball Trough'
    s_trough1:
        number: S26
        label: 'Left Ball Trough'
    s_shooter:
        number: S28
        label: 'Shooter Lane'
    s_up:
        number: S31
    s_down:
        number: S32
    s_enter:
        number: S33
    s_rampEntry:
        number: S34
        label: 'Ramp Entry'
    s_rightEject:
        number: S35
        label: 'Right Eject'
    s_midLeftEject:
        number: S36
        label: 'Left Center Eject'
    s_midRightEject:
        number: S37
        label: 'Right Center Eject'
    s_vUK:
        number: S38
        label: 'Ball Popper'
    s_leftRescue:
        number: S41
        label: 'Left Center Target'
        tags: playfield_active
    s_rightRescue:
        number: S42
        label: 'Right Center Target'
        tags: playfield_active
    s_debug:
        number: S43
    s_jetBumper:
        number: S44
        label: 'Pop Bumper'
        tags: playfield_active
    s_exit:
        number: S45
    s_lowerRampMade:
        number: S46
        label: 'Lower Ramp'
    s_middleRampMade:
        number: S47
        label: 'Middle Ramp'
    s_upperRampMade:
        number: S48
        label: 'Upper Ramp'
    s_lowerLeftT:
        number: S51
        label: 'Lower Left T'
        tags: playfield_active
    s_lowerLeftO:
        number: S52
        label: 'Lower Left O'
        tags: playfield_active
    s_lowerLeftM:
        number: S53
        label: 'Lower Left M'
        tags: playfield_active
    s_lowerRightT:
        number: S54
        label: 'Lower Right T'
        tags: playfield_active
    s_lowerRightA:
        number: S55
        label: 'Lower Right A'
        tags: playfield_active
    s_lowerRightC:
        number: S56
        label: 'Lower Right C'
        tags: playfield_active
    s_unused57:
        number: S57
    s_unused58:
        number: S58
    s_target3:
        number: S61
        label: 'Target - 3'
        tags: playfield_active
    s_target2:
        number: S62
        label: 'Target - 2'
    s_target1:
        tags: playfield_active
        number: S63
        label: 'Target - 1'
    s_target4:
        number: S64
        tags: playfield_active
        label: 'Target - 4'
    s_target5:
        number: S65
        label: 'Target - 5'
        tags: playfield_active
    s_target6:
        number: S66
        label: 'Target - 6'
        tags: playfield_active
    s_bonusXRight:
        tags: playfield_active
        number: S67
        label: 'Top Right Loop'
    s_spinner:
        number: S68
        label: 'Spinner'
        tags: playfield_active
    s_upperLeftT:
        number: S71
        label: 'Upper Left T'
        tags: playfield_active
    s_upperLeftO:
        number: S72
        label: 'Upper Left O'
        tags: playfield_active
    s_upperLeftM:
        number: S73
        label: 'Upper Left M'
        tags: playfield_active
    s_upperRightT:
        number: S74
        label: 'Upper Right T'
        tags: playfield_active
    s_upperRightA:
        number: S75
        label: 'Upper Right A'
        tags: playfield_active
    s_upperRightC:
        number: S76
        label: 'Upper Right C'
        tags: playfield_active
    s_yagov:
        number: S77
        label: 'Yagov'
        tags: playfield_active
    s_bonusXLeft:
        number: S78
        label: 'Top Left Loop'
        tags: playfield_active
    s_slingL:
        number: S81
        label: 'Left Sling'
        tags: playfield_active
    s_slingR:
        number: S82
        label: 'Right Sling'
        tags: playfield_active
    

