#config_version=5


#     ______            _____                            __        __              __
#    / ____/___  ____  / __(_)___ __    ________  ____ _/ /   ____/ /___ ___  ____/ /
#   / /   / __ \/ __ \/ /_/ / __ `(_)  / ___/ _ \/ __ `/ /   / __  / __ `__ \/ __  / 
#  / /___/ /_/ / / / / __/ / /_/ /    / /  /  __/ /_/ / /   / /_/ / / / / / / /_/ /  
#  \____/\____/_/ /_/_/ /_/\__, (_)  /_/   \___/\__,_/_/____\__,_/_/ /_/ /_/\__,_/   
#                         /____/                      /_____/                        

# Not actually using this, but did test it out when helping Jan :)
dmds:
  my_dmd:  # name of this DMD which can be whatever you want
    brightness: 1.0
    fps: 25
    gamma: 1.0
    source_display: dmd
    platform: p_roc
    
p_roc:
   dmd_timing_cycles: 90, 190, 50, 377
