#config_version=5


#     ______            _____                 _                 __               __                      
#    / ____/___  ____  / __(_)___ __    _____(_)___ ___  ____  / /__       _____/ /_  ____ _      _______
#   / /   / __ \/ __ \/ /_/ / __ `(_)  / ___/ / __ `__ \/ __ \/ / _ \     / ___/ __ \/ __ \ | /| / / ___/
#  / /___/ /_/ / / / / __/ / /_/ /    (__  ) / / / / / / /_/ / /  __/    (__  ) / / / /_/ / |/ |/ (__  ) 
#  \____/\____/_/ /_/_/ /_/\__, (_)  /____/_/_/ /_/ /_/ .___/_/\___/____/____/_/ /_/\____/|__/|__/____/  
#                         /____/                     /_/          /_____/                                

# Initially thought I needed to define these, but probably the default ones in MPF are enough
# TODO - remove this?
shows:
   blink:
      - time: 0
        lights:
           (lamp): on
      - time: +0.5s
        lights:
           (lamp): off
        duration: 0.5s
   lamp_on:
      - lights:
           (lamp): on
   lamp_blink:
      - lights:
           (lamp): on
        duration: 0.5s
   lamp_handler:
      - lights:
            (lamp): (state)