#config_version=5

shows:
   blink:
      - time: 0
        lights:
           (lamp): on
      - time: +0.5s
        lights:
           (lamp): off
        duration: 0.5s
   lamp_on:
      - lights:
           (lamp): on
   lamp_blink:
      - lights:
           (lamp): on
        duration: 0.5s
   lamp_handler:
      - lights:
            (lamp): (state)