#config_version=5

#      __  ___          __          __                                                    _       __    __ 
#     /  |/  /___  ____/ /__  _    / /_  __  ______________  __    __  ______       _____(_)___ _/ /_  / /_
#    / /|_/ / __ \/ __  / _ \(_)  / __ \/ / / / ___/ ___/ / / /   / / / / __ \     / ___/ / __ `/ __ \/ __/
#   / /  / / /_/ / /_/ /  __/    / / / / /_/ / /  / /  / /_/ /   / /_/ / /_/ /    / /  / / /_/ / / / / /_  
#  /_/  /_/\____/\__,_/\___(_)  /_/ /_/\__,_/_/  /_/   \__, /____\__,_/ .___/____/_/  /_/\__, /_/ /_/\__/  
#                                                     /____/_____/   /_/   /_____/      /____/             


# Right hand side hurry-up, started by left inlane
# TODO - check what happens if we repeat the hurry up with launch bonus 250k - here assumes we continue to score 250k each time......
# TODO - when does the launch bonus reset?  Each ball?  Or every time we get to 250k?

mode:
   start_events: s_inlaneLeft_active
   stop_events: ball_ending, timer_hurry_up_right_complete
   priority: 110 # so the lamp show will cover other stuff
   
event_player:
   s_vUK_active{current_player.launch_bonus < 250000}:
      increment_launch_bonus
   s_vUK_active{current_player.launch_bonus == 250000}:
      score_launch_bonus
      
variable_player:
   increment_launch_bonus:
      launch_bonus: 50000
      score: current_player.launch_bonus
   score_launch_bonus:
      score: current_player.launch_bonus
      
slide_player:
   player_launch_bonus:
      slide:
        target: dmd
        expire: 1s
        widgets:
          - type: text
            text: LAUNCH BONUS (launch_bonus)
            number_grouping: yes
            font_size: 15
            color: white               
      

timers:
   hurry_up_right:
      start_value: 0
      end_value: 26
      direction: up
      tick_interval: 0.1s
      control_events:
         - event: s_inlaneLeft_active # reset the hurry-up if we get the inlane again
           action: reset
      start_running: true
            
show_player:
   mode_hurry_up_right_started: # Do this right at the start of the mode to turn off the indicator lamps
      off:
        show_tokens: 
          light: l_bonus1K l_bonus2K l_bonus4K l_bonus8K l_bonus16K l_bonus32K l_bonus64K l_lockOn l_release l_landing
   timer_hurry_up_right_tick{ticks==1}: hurry_right # and start the show once we hit the first tick of the timer
   
   
      

shows:
   hurry_right:
      - duration: 0.1
        lights : 
              l_bonus1K : on
      - duration: 0.1
        lights :
              l_bonus1K : on
              l_bonus2K : on
      - duration: 0.1
        lights :
              l_bonus1K : on
              l_bonus2K : on
              l_bonus4K : on
      - duration: 0.1
        lights :
              l_bonus1K : off
              l_bonus8K : on
      - duration: 0.1
        lights :
              l_bonus2K : off
              l_bonus16K : on
      - duration: 0.1
        lights :
              l_bonus4K : off
              l_bonus32K : on
      - duration: 0.1
        lights :
              l_bonus8K : off
              l_bonus64K : on
      - duration: 0.1
        lights :
              l_bonus16K : off
              l_lockOn: on
      - duration: 0.1
        lights :
              l_bonus32K : off
              l_release: on
      - duration: 0.1
        lights :
              l_bonus64K : off
              l_landing: on
      - duration: 0.1
        lights :
              l_lockOn : off
      - duration: 0.1
        lights :
              l_release : off
      - duration: 0.1
        lights :
              l_landing : off

 